language: node_js
node_js:
  - "stable"
before_install:
  - export CHROME_BIN=chromium-browser
services:
  - xvfb

script:
  - npm install
  - npm install -g bower
  - npm install -g grunt-cli
  - gem install compass
  - cd ui && npm install
  - cat npm-debug.log || true
  - bower install



