language: node_js
node_js: "10"
sudo: required
services:
  - xvfb
before_install:
  - if [[ `npm -v` == 3.10.8 ]]; then npm i -g npm@3.10.7; fi
  - npm --version
  - npm config set spin false


install:
  - npm install -g bower
  - npm install -g grunt-cli
  - gem install compass
  - cd ui && npm install
  - cat npm-debug.log || true
  - bower install

script: grunt bundle && grunt uglify-and-rename && grunt web

cache:
  directories:
    - ui/node_modules
    - ui/app/components

notifications:
  email: false
